### ISSUE TITLE
Image file causing compile error

### ISSUE THREAD

**Issue by gordon13** [paulcpederson/static-site#14]
I'm getting a strange error when building my site with a specific image. The error is shown below.

```
C:\Users\paull\site>npm run build

> site@1.0.0 build C:\Users\paull\site
> static-site --prettyUrl false

��'�;����m��/��F�l��'7y"�Ayv������xm�^�A㘋��&�멗�ݝA���U���r������o��&n���&�ra3~�5B�g���7~;���
��ل1k�ޞV��x`l����@Ε~A�{��������jio������멢��J��T�(W����\���~��\Z��#�ǲ�l���43[+�G�����G6-Hϡ��QH1-���ف7�U���+�G%�e     ���L�0�u�r�@���H�'�,F����*�]Ze�ڐ R�HE5ec�8HZ1G A{�%Ȓ�"Z�WHG�H
�_� b$P�Z/����2������%5*������ HcAD����<�eq�3�d����@2u��2��o _�Αx�>o�/EY�(�%�j�@�*k)O�%���l�e��n�M+A�E�[$�Z�~,Fy\b�>�\�6ܴ����<�k{�������#��ؑ^W I �XT �Mg�]t��.:�n:��c�B9m�1,���{c8��8
K!�s���"���\��Ӣlc����� �  *�    ���#t��Q�)�x� \:��.��<IW>9EW?WN�5��U<��矅�}��g#.'�3�+1ཹ y�Þ�軧��w�G�Iͣ
... lots more but I removed it for this ...
 on line 327 in file C:/Users/paull/site/source/img/background2.png.��G�D�Xj�<@RxcK�#���2Kk(��V1�� y5
    at Object.exports.throwError (C:\Users\paull\AppData\Roaming\npm\node_modules\static-site\node_modules\swig-templates\lib\utils.js:188:9)�1f)YX9���GIC�3
    at parseTag (C:\Users\paull\AppData\Roaming\npm\node_modules\static-site\node_modules\swig-templates\lib\parser.js:675:13)�,g�QAXI5H��R��B"��',�x�}4�@`�X��<�O� "���|*�0��?p���+�� V ���q"��c�����6Ȭ�i��@�G ��&`K��
    at C:\Users\paull\AppData\Roaming\npm\node_modules\static-site\node_modules\swig-templates\lib\parser.js:778:15�
    at Object.exports.each (C:\Users\paull\AppData\Roaming\npm\node_modules\static-site\node_modules\swig-templates\lib\utils.js:45:11)
    at Object.exports.parse (C:\Users\paull\AppData\Roaming\npm\node_modules\static-site\node_modules\swig-templates\lib\parser.js:755:9)
    at exports.Swig.parse (C:\Users\paull\AppData\Roaming\npm\node_modules\static-site\node_modules\swig-templates\lib\swig.js:383:19)
    at exports.Swig.precompile (C:\Users\paull\AppData\Roaming\npm\node_modules\static-site\node_modules\swig-templates\lib\swig.js:526:23)
    at exports.Swig.compile (C:\Users\paull\AppData\Roaming\npm\node_modules\static-site\node_modules\swig-templates\lib\swig.js:651:16)
    at Object.render (C:\Users\paull\AppData\Roaming\npm\node_modules\static-site\node_modules\swig-templates\lib\swig.js:570:17)
    at Object.swigTemplate (C:\Users\paull\AppData\Roaming\npm\node_modules\static-site\lib\template.js:46:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! exodus-orbitals@1.0.0 build: `static-site --prettyUrl false`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the exodus-orbitals@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\paull\AppData\Roaming\npm-cache\_logs\2019-05-18T14_53_34_481Z-debug.log
```

I tried converting the image from png format to jpg but the same issue occurs. 

I also have a few other images in there that don't cause any issues including an svg.

Any ideas why an image would cause this error, am I using static-site wrong or is this a bug?

**Comment by paulcpederson** [comment]
static-site is not meant to handle images. Most likely what's happening is that you're passing a png/jpg to static site as if it's a template, then swig can't make heads or tails so it throws an error. 

Images should be copied to the destination folder, static site shouldn't even know about them, if that makes sense.

**Comment by gordon13** [comment]
Yes that makes a lot of sense now. I made a file copy script that runs after compile and everything is fine.
________________________________
